best_args = {'perm-mnist': {
    'sgd': {-1: {'lr': 0.2, 'batch_size': 128, 'n_epochs': 1}},
    'ewc_on': {-1: {'lr': 0.1,
                    'e_lambda': 200,
                    'gamma': 1.0,
                    'batch_size': 128,
                    'n_epochs': 1}},
    'si': {-1: {'lr': 0.1,
                'c': 0.5,
                'xi': 1.0,
                'batch_size': 128,
                'n_epochs': 1}},
    'lwf': {-1: {'lr': 0.01,
                 'alpha': 0.5,
                 'softmax_temp': 2.0,
                 'batch_size': 128,
                 'n_epochs': 1}},
    'er': {200: {'lr': 0.2,
                   'minibatch_size': 128,
                   'batch_size': 128,
                   'n_epochs': 1},
           500: {'lr': 0.2,
                   'minibatch_size': 128,
                   'batch_size': 128,
                   'n_epochs': 1},
           5120: {'lr': 0.2,
                    'minibatch_size': 128,
                    'batch_size': 128,
                    'n_epochs': 1}},
    'gem': {200: {'lr': 0.1,
                    'gamma': 0.5,
                    'batch_size': 128,
                    'n_epochs': 1},
            500: {'lr': 0.1, 'gamma': 0.5, 'batch_size': 128,
                    'n_epochs': 1},
            5120: {'lr': 0.1, 'gamma': 0.5, 'batch_size': 128,
                     'n_epochs': 1}},
    'agem': {200: {'lr': 0.1,
                     'minibatch_size': 256,
                     'batch_size': 128,
                     'n_epochs': 1},
             500: {'lr': 0.1,
                     'minibatch_size': 128,
                     'batch_size': 128,
                     'n_epochs': 1},
             5120: {'lr': 0.1,
                      'minibatch_size': 256,
                      'batch_size': 128,
                      'n_epochs': 1}},
'agem_r': {200: {'lr': 0.1,
                     'minibatch_size': 256,
                     'batch_size': 128,
                     'n_epochs': 1},
             500: {'lr': 0.1,
                     'minibatch_size': 128,
                     'batch_size': 128,
                     'n_epochs': 1},
             5120: {'lr': 0.1,
                      'minibatch_size': 256,
                      'batch_size': 128,
                      'n_epochs': 1}},
    'der': {200: {'lr': 0.2,
                    'minibatch_size': 128,
                    'alpha': 1.0,
                    'batch_size': 128,
                    'n_epochs': 1},
            500: {'lr': 0.2,
                    'minibatch_size': 128,
                    'alpha': 1.0,
                    'batch_size': 128,
                    'n_epochs': 1},
            5120: {'lr': 0.2,
                     'minibatch_size': 128,
                     'alpha': 0.5,
                     'batch_size': 128,
                     'n_epochs': 1}},
    'derpp': {200: {'lr': 0.1,
                      'minibatch_size': 128,
                      'alpha': 1.0,
                      'beta': 1.0,
                      'batch_size': 128,
                      'n_epochs': 1},
              500: {'lr': 0.2,
                      'minibatch_size': 128,
                      'alpha': 1.0,
                      'beta': 0.5,
                      'batch_size': 128,
                      'n_epochs': 1},
              5120: {'lr': 0.2,
                       'minibatch_size': 128,
                       'alpha': 0.5,
                       'beta': 1.0,
                       'batch_size': 128,
                       'n_epochs': 1}}},
             'rot-mnist': {
                 'sgd': {-1: {'lr': 0.2, 'batch_size': 128, 'n_epochs': 1}},
                 'ewc_on': {-1: {'lr': 0.1,
                                 'e_lambda': 200,
                                 'gamma': 1.0,
                                 'batch_size': 128,
                                 'n_epochs': 1}},
                 'si': {-1: {'lr': 0.1,
                             'c': 1.0,
                             'xi': 1.0,
                             'batch_size': 128,
                             'n_epochs': 1}},
                 'lwf': {-1: {'lr': 0.2,
                              'alpha': 1.0,
                              'softmax_temp': 2.0,
                              'batch_size': 128,
                              'n_epochs': 1}},
                 'er': {200: {'lr': 0.2,
                                'minibatch_size': 128,
                                'batch_size': 128,
                                'n_epochs': 1},
                        500: {'lr': 0.2,
                                'minibatch_size': 128,
                                'batch_size': 128,
                                'n_epochs': 1},
                        5120: {'lr': 0.2,
                                 'minibatch_size': 128,
                                 'batch_size': 128,
                                 'n_epochs': 1}},
                 'gem': {200: {'lr': 0.01,
                                 'gamma': 0.5,
                                 'batch_size': 128,
                                 'n_epochs': 1},
                         500: {'lr': 0.01, 'gamma': 0.5, 'batch_size': 128,
                                 'n_epochs': 1},
                         5120: {'lr': 0.01, 'gamma': 0.5, 'batch_size': 128,
                                  'n_epochs': 1}},
                 'agem': {200: {'lr': 0.1,
                                  'minibatch_size': 256,
                                  'batch_size': 128,
                                  'n_epochs': 1},
                          500: {'lr': 0.3,
                                  'minibatch_size': 256,
                                  'batch_size': 128,
                                  'n_epochs': 1},
                          5120: {'lr': 0.3,
                                   'minibatch_size': 128,
                                   'batch_size': 128,
                                   'n_epochs': 1}},
                 'agem_r': {200: {'lr': 0.1,
                                  'minibatch_size': 256,
                                  'batch_size': 128,
                                  'n_epochs': 1},
                          500: {'lr': 0.3,
                                  'minibatch_size': 256,
                                  'batch_size': 128,
                                  'n_epochs': 1},
                          5120: {'lr': 0.3,
                                   'minibatch_size': 128,
                                   'batch_size': 128,
                                   'n_epochs': 1}},
                 'der': {200: {'lr': 0.2,
                                 'minibatch_size': 128,
                                 'alpha': 1.0,
                                 'batch_size': 128,
                                 'n_epochs': 1},
                         500: {'lr': 0.2,
                                 'minibatch_size': 128,
                                 'alpha': 0.5,
                                 'batch_size': 128,
                                 'n_epochs': 1},
                         5120: {'lr': 0.2,
                                  'minibatch_size': 128,
                                  'alpha': 0.5,
                                  'batch_size': 128,
                                  'n_epochs': 1}},
                 'derpp': {200: {'lr': 0.1,
                                   'minibatch_size': 128,
                                   'alpha': 1.0,
                                   'beta': 0.5,
                                   'batch_size': 128,
                                   'n_epochs': 1},
                           500: {'lr': 0.2,
                                   'minibatch_size': 128,
                                   'alpha': 0.5,
                                   'beta': 1.0,
                                   'batch_size': 128,
                                   'n_epochs': 1},
                           5120: {'lr': 0.2,
                                    'minibatch_size': 128,
                                    'alpha': 0.5,
                                    'beta': 0.5,
                                    'batch_size': 128,
                                    'n_epochs': 1}}},
             'seq-mnist': {
                 'sgd': {-1: {'lr': 0.1, 'batch_size': 10, 'n_epochs': 1}},
                 'ewc_on': {-1: {'lr': 0.03,
                                 'e_lambda': 90,
                                 'gamma': 1.0,
                                 'batch_size': 10,
                                 'n_epochs': 1}},
                 'si': {-1: {'lr': 0.03,
                             'c': 1.0,
                             'xi': 1.0,
                             'batch_size': 10,
                             'n_epochs': 1}},
                 'lwf': {-1: {'lr': 0.03,
                              'alpha': 1.0,
                              'softmax_temp': 2.0,
                              'batch_size': 10,
                              'n_epochs': 1}},
                 'pnn': {-1: {'lr': 0.1, 'batch_size': 10, 'n_epochs': 1}},
                 'er': {200: {'lr': 0.1,
                                'minibatch_size': 128,
                                'batch_size': 10,
                                'n_epochs': 1},
                        500: {'lr': 0.2,
                                'minibatch_size': 64,
                                'batch_size': 10,
                                'n_epochs': 1},
                        5120: {'lr': 0.2,
                                 'minibatch_size': 128,
                                 'batch_size': 10,
                                 'n_epochs': 1}},
                 'mer': {200: {'lr': 0.1,
                                 'minibatch_size': 128,
                                 'beta': 1,
                                 'gamma': 1,
                                 'batch_num': 3,
                                 'batch_size': 10,
                                 'n_epochs': 1},
                         500: {'lr': 0.03,
                                 'minibatch_size': 128,
                                 'beta': 1,
                                 'gamma': 1,
                                 'batch_num': 3,
                                 'batch_size': 10,
                                 'n_epochs': 1},
                         5120: {'lr': 0.1,
                                  'minibatch_size': 128,
                                  'beta': 1,
                                  'gamma': 1,
                                  'batch_num': 3,
                                  'batch_size': 10,
                                  'n_epochs': 1}},
                 'gem': {200: {'lr': 0.1,
                                 'gamma': 0.5,
                                 'batch_size': 10,
                                 'n_epochs': 1},
                         500: {'lr': 0.1, 'gamma': 0.5, 'batch_size': 10,
                                 'n_epochs': 1},
                         5120: {'lr': 0.1, 'gamma': 0.5, 'batch_size': 10,
                                  'n_epochs': 1}},
                 'agem': {200: {'lr': 0.1,
                                  'minibatch_size': 128,
                                  'batch_size': 10,
                                  'n_epochs': 1},
                          500: {'lr': 0.1,
                                  'minibatch_size': 128,
                                  'batch_size': 10,
                                  'n_epochs': 1},
                          5120: {'lr': 0.1,
                                   'minibatch_size': 128,
                                   'batch_size': 10,
                                   'n_epochs': 1}},
                 'agem_r': {200: {'lr': 0.1,
                                  'minibatch_size': 128,
                                  'batch_size': 10,
                                  'n_epochs': 1},
                          500: {'lr': 0.1,
                                  'minibatch_size': 128,
                                  'batch_size': 10,
                                  'n_epochs': 1},
                          5120: {'lr': 0.1,
                                   'minibatch_size': 128,
                                   'batch_size': 10,
                                   'n_epochs': 1}},
                 'icarl': {200: {'lr': 0.2,
                                   'minibatch_size': 10,
                                   'softmax_temp': 2.0,
                                   'wd_reg': 0.0005,
                                   'batch_size': 10,
                                   'n_epochs': 1},
                           500: {'lr': 0.2,
                                   'minibatch_size': 10,
                                   'softmax_temp': 2.0,
                                   'wd_reg': 0.0005,
                                   'batch_size': 10,
                                   'n_epochs': 1},
                           5120: {'lr': 0.2,
                                    'minibatch_size': 10,
                                    'softmax_temp': 2.0,
                                    'wd_reg': 0.0005,
                                    'batch_size': 10,
                                    'n_epochs': 1}},
                 'der': {200: {'lr': 0.03,
                                 'minibatch_size': 10,
                                 'alpha': 0.2,
                                 'batch_size': 10,
                                 'n_epochs': 1},
                         500: {'lr': 0.1,
                                 'minibatch_size': 128,
                                 'alpha': 1.0,
                                 'batch_size': 10,
                                 'n_epochs': 1},
                         5120: {'lr': 0.2,
                                  'minibatch_size': 128,
                                  'alpha': 1.0,
                                  'batch_size': 10,
                                  'n_epochs': 1}},
                 'derpp': {200: {'lr': 0.03,
                                   'minibatch_size': 128,
                                   'alpha': 0.2,
                                   'beta': 1.0,
                                   'batch_size': 10,
                                   'n_epochs': 1},
                           500: {'lr': 0.1,
                                   'minibatch_size': 10,
                                   'alpha': 0.5,
                                   'beta': 1.0,
                                   'batch_size': 10,
                                   'n_epochs': 1},
                           5120: {'lr': 0.1,
                                    'minibatch_size': 64,
                                    'alpha': 0.5,
                                    'beta': 1.0,
                                    'batch_size': 10,
                                    'n_epochs': 1}}},
             'seq-cifar10': {'sgd': {-1: {'lr': 0.1,
                                          'batch_size': 32,
                                          'n_epochs': 50}},
                             'ewc_on': {-1: {'lr': 0.03,
                                             'e_lambda': 400,
                                             'gamma': 1.0,
                                             'batch_size': 32,
                                             'n_epochs': 50}},
                             'si': {-1: {'lr': 0.03,
                                         'c': 0.5,
                                         'xi': 1.0,
                                         'batch_size': 32,
                                         'n_epochs': 50}},
                             'lwf': {-1: {'lr': 0.03,
                                          'alpha': 0.5,
                                          'softmax_temp': 2.0,
                                          'batch_size': 32,
                                          'n_epochs': 50}},
                             'pnn': {-1: {'lr': 0.03, 'batch_size': 32,
                                          'n_epochs': 50}},
                             'er': {200: {'lr': 0.1,
                                            'minibatch_size': 128,
                                            'batch_size': 32,
                                            'n_epochs': 50},
                                    500: {'lr': 0.1,
                                            'minibatch_size': 128,
                                            'batch_size': 32,
                                            'n_epochs': 50},
                                    5120: {'lr': 0.1,
                                             'minibatch_size': 128,
                                             'batch_size': 32,
                                             'n_epochs': 50}},
                             'gem': {200: {'lr': 0.03,
                                             'gamma': 0.5,
                                             'batch_size': 32,
                                             'n_epochs': 50},
                                     500: {'lr': 0.03, 'gamma': 0.5,
                                             'batch_size': 32,
                                             'n_epochs': 50},
                                     5120: {'lr': 0.03, 'gamma': 0.5,
                                              'batch_size': 32,
                                              'n_epochs': 50}},
                             'agem': {200: {'lr': 0.03,
                                              'minibatch_size': 32,
                                              'batch_size': 32,
                                              'n_epochs': 50},
                                      500: {'lr': 0.03,
                                              'minibatch_size': 128,
                                              'batch_size': 32,
                                              'n_epochs': 50},
                                      5120: {'lr': 0.03,
                                               'minibatch_size': 128,
                                               'batch_size': 32,
                                               'n_epochs': 50}},
                             'agem_r': {200: {'lr': 0.03,
                                              'minibatch_size': 32,
                                              'batch_size': 32,
                                              'n_epochs': 50},
                                      500: {'lr': 0.03,
                                              'minibatch_size': 128,
                                              'batch_size': 32,
                                              'n_epochs': 50},
                                      5120: {'lr': 0.03,
                                               'minibatch_size': 128,
                                               'batch_size': 32,
                                               'n_epochs': 50}},
                             'icarl': {200: {'lr': 0.1,
                                               'minibatch_size': 32,
                                               'softmax_temp': 2.0,
                                               'wd_reg': 0.0005,
                                               'batch_size': 32,
                                               'n_epochs': 50},
                                       500: {'lr': 0.03,
                                               'minibatch_size': 32,
                                               'softmax_temp': 2.0,
                                               'wd_reg': 0.0005,
                                               'batch_size': 32,
                                               'n_epochs': 50},
                                       5120: {'lr': 0.1,
                                                'minibatch_size': 128,
                                                'softmax_temp': 2.0,
                                                'wd_reg': 0.0005,
                                                'batch_size': 32,
                                                'n_epochs': 50}},
                             'der': {200: {'lr': 0.03,
                                             'minibatch_size': 32,
                                             'alpha': 0.2,
                                             'batch_size': 32,
                                             'n_epochs': 50},
                                     500: {'lr': 0.03,
                                             'minibatch_size': 32,
                                             'alpha': 0.2,
                                             'batch_size': 32,
                                             'n_epochs': 50},
                                     5120: {'lr': 0.03,
                                              'minibatch_size': 32,
                                              'alpha': 0.2,
                                              'batch_size': 32,
                                              'n_epochs': 50}},
                             'derpp': {200: {'lr': 0.03,
                                               'minibatch_size': 32,
                                               'alpha': 0.1,
                                               'beta': 0.5,
                                               'batch_size': 32,
                                               'n_epochs': 50},
                                       500: {'lr': 0.03,
                                               'minibatch_size': 32,
                                               'alpha': 0.2,
                                               'beta': 0.5,
                                               'batch_size': 32,
                                               'n_epochs': 50},
                                       5120: {'lr': 0.03,
                                                'minibatch_size': 32,
                                                'alpha': 0.1,
                                                'beta': 1.0,
                                                'batch_size': 32,
                                                'n_epochs': 50}}},
             'seq-tinyimg': {'sgd': {-1: {'lr': 0.03,
                                          'batch_size': 32,
                                          'n_epochs': 100}},
                             'ewc_on': {-1: {'lr': 0.03,
                                             'e_lambda': 200,
                                             'gamma': 1.0,
                                             'batch_size': 32,
                                             'n_epochs': 100}},
                             'si': {-1: {'lr': 0.03,
                                         'c': 0.5,
                                         'xi': 1.0,
                                         'batch_size': 32,
                                         'n_epochs': 100}},
                             'lwf': {-1: {'lr': 0.03,
                                          'alpha': 0.5,
                                          'softmax_temp': 2.0,
                                          'batch_size': 32,
                                          'n_epochs': 100}},
                             'pnn': {-1: {'lr': 0.03, 'batch_size': 32,
                                          'n_epochs': 100}},
                             'er': {200: {'lr': 0.1,
                                            'minibatch_size': 32,
                                            'batch_size': 32,
                                            'n_epochs': 100},
                                    500: {'lr': 0.03,
                                            'minibatch_size': 32,
                                            'batch_size': 32,
                                            'n_epochs': 100},
                                    5120: {'lr': 0.1,
                                             'minibatch_size': 32,
                                             'batch_size': 32,
                                             'n_epochs': 100}},
                             'agem': {200: {'lr': 0.01,
                                              'minibatch_size': 32,
                                              'batch_size': 32,
                                              'n_epochs': 100},
                                      500: {'lr': 0.01,
                                              'minibatch_size': 32,
                                              'batch_size': 32,
                                              'n_epochs': 100},
                                      5120: {'lr': 0.01,
                                               'minibatch_size': 32,
                                               'batch_size': 32,
                                               'n_epochs': 100}},
                             'agem_r': {200: {'lr': 0.01,
                                              'minibatch_size': 32,
                                              'batch_size': 32,
                                              'n_epochs': 100},
                                      500: {'lr': 0.01,
                                              'minibatch_size': 32,
                                              'batch_size': 32,
                                              'n_epochs': 100},
                                      5120: {'lr': 0.01,
                                               'minibatch_size': 32,
                                               'batch_size': 32,
                                               'n_epochs': 100}},
                             'icarl': {200: {'lr': 0.03,
                                               'minibatch_size': 32,
                                               'softmax_temp': 2.0,
                                               'wd_reg': 0.0005,
                                               'batch_size': 32,
                                               'n_epochs': 100},
                                       500: {'lr': 0.03,
                                               'minibatch_size': 32,
                                               'softmax_temp': 2.0,
                                               'wd_reg': 0.0005,
                                               'batch_size': 32,
                                               'n_epochs': 100},
                                       5120: {'lr': 0.03,
                                                'minibatch_size': 32,
                                                'softmax_temp': 2.0,
                                                'wd_reg': 0.0005,
                                                'batch_size': 32,
                                                'n_epochs': 100}},
                             'der': {200: {'lr': 0.03,
                                             'minibatch_size': 32,
                                             'softmax_temp': 2.0,
                                             'alpha': 0.2,
                                             'batch_size': 32,
                                             'n_epochs': 100},
                                     500: {'lr': 0.03,
                                             'minibatch_size': 32,
                                             'alpha': 0.2,
                                             'batch_size': 32,
                                             'n_epochs': 100},
                                     5120: {'lr': 0.03,
                                              'minibatch_size': 32,
                                              'alpha': 0.2,
                                              'batch_size': 32,
                                              'n_epochs': 100}},
                             'derpp': {200: {'lr': 0.03,
                                               'minibatch_size': 32,
                                               'alpha': 0.1,
                                               'beta': 1.0,
                                               'batch_size': 32,
                                               'n_epochs': 100},
                                       500: {'lr': 0.03,
                                               'minibatch_size': 32,
                                               'alpha': 0.2,
                                               'beta': 0.5,
                                               'batch_size': 32,
                                               'n_epochs': 100},
                                       5120: {'lr': 0.03,
                                                'minibatch_size': 32,
                                                'alpha': 0.1,
                                                'beta': 0.5,
                                                'batch_size': 32,
                                                'n_epochs': 100}}},
             'mnist-360': {
                 'sgd': {-1: {'lr': 0.1, 'batch_size': 4}},
                 'er': {200: {'lr': 0.2,
                                'batch_size': 1,
                                'minibatch_size': 16},
                        500: {'lr': 0.2, 'batch_size': 1,
                                'minibatch_size': 16},
                        1000: {'lr': 0.2,
                                 'batch_size': 4,
                                 'minibatch_size': 16}},
                 'mer': {200: {'lr': 0.2,
                                 'minibatch_size': 128,
                                 'beta': 1,
                                 'gamma': 1,
                                 'batch_num': 3},
                         500: {'lr': 0.1,
                                 'minibatch_size': 128,
                                 'beta': 1,
                                 'gamma': 1,
                                 'batch_num': 3},
                         1000: {'lr': 0.2,
                                  'minibatch_size': 128,
                                  'beta': 1,
                                  'gamma': 1,
                                  'batch_num': 3}},
                 'agem_r': {200: {'lr': 0.1,
                                  'batch_size': 16,
                                  'minibatch_size': 128},
                            500: {'lr': 0.1,
                                    'batch_size': 16,
                                    'minibatch_size': 128},
                            1000: {'lr': 0.1,
                                     'batch_size': 4,
                                     'minibatch_size': 128}},
                 'der': {200: {'lr': 0.1,
                                 'batch_size': 16,
                                 'minibatch_size': 64,
                                 'alpha': 0.5},
                         500: {'lr': 0.2,
                                 'batch_size': 16,
                                 'minibatch_size': 16,
                                 'alpha': 0.5},
                         1000: {'lr': 0.1,
                                  'batch_size': 8,
                                  'minibatch_size': 16,
                                  'alpha': 0.5}},
                 'derpp': {200: {'lr': 0.2,
                                   'batch_size': 16,
                                   'minibatch_size': 16,
                                   'alpha': 0.5,
                                   'beta': 1.0},
                           500: {'lr': 0.2,
                                   'batch_size': 16,
                                   'minibatch_size': 16,
                                   'alpha': 0.5,
                                   'beta': 1.0},
                           1000: {'lr': 0.2,
                                    'batch_size': 16,
                                    'minibatch_size': 128,
                                    'alpha': 0.2,
                                    'beta': 1.0}}}}
